FROM python:3.8-slim
LABEL maintainer="u6k.apps@gmail.com"

# Install softwares
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    pip install -U pip && \
    pip install pipenv

# Install python packages
WORKDIR /var/myapp

COPY . /var/myapp
RUN pipenv sync

CMD ["pipenv", "scripts"]
